# Generated by Django 4.0.3 on 2022-08-04 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('type', models.IntegerField(choices=[(0, 'Project'), (1, 'Document'), (2, 'Diagram')])),
                ('includeFile', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('belongTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
                ('deletedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diagram',
            name='deleteRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deletion'),
        ),
        migrations.AddField(
            model_name='document',
            name='deleteRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deletion'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleteRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deletion'),
        ),
    ]
