# Generated by Django 4.0.3 on 2022-08-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deletion_diagram_deleterecord_document_deleterecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='content',
            field=models.JSONField(null=True),
        ),
    ]
