# Generated by Django 4.0.3 on 2022-08-04 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invitation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='teamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitedBy',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='team',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
