# Generated by Django 4.0.3 on 2022-08-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invitation_teamid_alter_invitation_invitedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitedBy',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='team',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
