# Generated by Django 4.0.3 on 2022-08-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_project_invitation_document_userteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(max_length=50000),
        ),
    ]
