# Generated by Django 4.0.3 on 2022-08-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invitation_invitedby_alter_invitation_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='teamImg',
            field=models.ImageField(blank=True, upload_to='uploads/invitation'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='team',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
