# Generated by Django 4.0.3 on 2022-08-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_diagram_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
