# Generated by Django 4.0.3 on 2022-08-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_is_active_invitation_invitedby_and_more'),
        ('api', '0006_userteam_updatedat_userproject'),
    ]

    operations = [
    ]
