# Generated by Django 4.0.3 on 2022-08-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='canvasStyleData',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='componentData',
            field=models.TextField(max_length=10000),
        ),
    ]
