# Generated by Django 4.0.3 on 2022-08-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_diagram_canvasstyledata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='canvasStyleData',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='componentData',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
