# Generated by Django 4.0.3 on 2022-08-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_diagram_canvasstyledata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='componentData',
            field=models.TextField(blank=True, max_length=500000, null=True),
        ),
    ]
